openapi: "3.0.0"
info:
  version: 0.0.0
  title: ivory-beam API
servers:
  - url: http://ivory-beam.example/beta
paths:
  /cafeterias:
    get:
      summary: List all cafeterias
      responses:
        200:
          description: Array of cafeterias
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CafeteriaArray"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create new cafeteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cafeteria"
      responses:
        201:
          description: Null response
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cafeteria:
      required:
        - id
        - name
        - capacity
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        capacity:
          type: integer
      example:
        id: 1
        name: "Kubuś"
        capacity: 50
    CafeteriaArray:
      type: array
      items:
        $ref: "#/components/schemas/Cafeteria"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
