swagger: '2.0'
info:
  title: EatersLab API
  version: v1
host: eaterslab.herokuapp.com
schemes:
  - https
basePath: /api/beta
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /cafeterias/:
    get:
      operationId: cafeterias_list
      description: ''
      parameters:
        - name: opened_from
          in: query
          description: ''
          required: false
          type: string
        - name: opened_to
          in: query
          description: ''
          required: false
          type: string
        - name: opened_now
          in: query
          description: ''
          required: false
          type: string
        - name: prefix_name
          in: query
          description: ''
          required: false
          type: string
        - name: owner_id
          in: query
          description: ''
          required: false
          type: number
        - name: have_vegs
          in: query
          description: ''
          required: false
          type: string
        - name: min_avg_review
          in: query
          description: ''
          required: false
          type: number
        - name: Accept-Language
          in: header
          description: Language for response content
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Cafeteria'
      tags:
        - cafeterias
    parameters: []
  /cafeterias/{cafeteria_pk}/fixed_menu_options/:
    get:
      operationId: cafeterias_fixed_menu_options_list
      description: ''
      parameters:
        - name: Accept-Language
          in: header
          description: Language for response content
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/FixedMenuOption'
      tags:
        - cafeterias
    parameters:
      - name: cafeteria_pk
        in: path
        required: true
        type: string
  /cafeterias/{cafeteria_pk}/fixed_menu_options/{id}/:
    get:
      operationId: cafeterias_fixed_menu_options_read
      description: ''
      parameters:
        - name: Accept-Language
          in: header
          description: Language for response content
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/FixedMenuOption'
      tags:
        - cafeterias
    parameters:
      - name: cafeteria_pk
        in: path
        required: true
        type: string
      - name: id
        in: path
        required: true
        type: string
  /cafeterias/{cafeteria_pk}/fixed_menu_options/{option_pk}/reviews/:
    get:
      operationId: cafeterias_fixed_menu_options_reviews_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/FixedMenuOptionReview'
      tags:
        - cafeterias
    parameters:
      - name: cafeteria_pk
        in: path
        required: true
        type: string
      - name: option_pk
        in: path
        required: true
        type: string
  /cafeterias/{cafeteria_pk}/fixed_menu_options/{option_pk}/reviews/{id}/:
    get:
      operationId: cafeterias_fixed_menu_options_reviews_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/FixedMenuOptionReview'
      tags:
        - cafeterias
    parameters:
      - name: cafeteria_pk
        in: path
        required: true
        type: string
      - name: id
        in: path
        required: true
        type: string
      - name: option_pk
        in: path
        required: true
        type: string
  /cafeterias/{cafeteria_pk}/stats/avg_dish_review:
    get:
      operationId: cafeterias_stats_avg_dish_review_list
      description: ''
      parameters:
        - name: start_timestamp
          in: query
          description: ''
          required: false
          type: string
        - name: end_timestamp
          in: query
          description: ''
          required: false
          type: string
        - name: count
          in: query
          description: ''
          required: false
          type: number
        - name: group_by
          in: query
          description: ''
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/AverageDishReviewStats'
      tags:
        - cafeterias
    parameters:
      - name: cafeteria_pk
        in: path
        required: true
        type: string
  /cafeterias/{cafeteria_pk}/stats/occupancy:
    get:
      operationId: cafeterias_stats_occupancy_list
      description: ''
      parameters:
        - name: start_timestamp
          in: query
          description: ''
          required: false
          type: string
        - name: end_timestamp
          in: query
          description: ''
          required: false
          type: string
        - name: count
          in: query
          description: ''
          required: false
          type: number
        - name: group_by
          in: query
          description: ''
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/OccupancyStats'
      tags:
        - cafeterias
    parameters:
      - name: cafeteria_pk
        in: path
        required: true
        type: string
  /cafeterias/{id}/:
    get:
      operationId: cafeterias_read
      description: ''
      parameters:
        - name: Accept-Language
          in: header
          description: Language for response content
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Cafeteria'
      tags:
        - cafeterias
    parameters:
      - name: id
        in: path
        description: "A unique integer value identifying this sto\u0142\xF3wka."
        required: true
        type: integer
  /cameras/{camera_pk}/events/:
    post:
      operationId: cameras_events_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/CameraEvent'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CameraEvent'
      tags:
        - cameras
    parameters:
      - name: camera_pk
        in: path
        required: true
        type: string
  /fixed_menu_reviews/:
    post:
      operationId: fixed_menu_reviews_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/FixedMenuOptionReview'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/FixedMenuOptionReview'
      tags:
        - fixed_menu_reviews
    parameters: []
  /upload/artifacts/beta/{filename}/:
    put:
      operationId: upload_artifacts_beta_update
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      consumes: []
      tags:
        - upload
    parameters:
      - name: filename
        in: path
        required: true
        type: string
  /upload/artifacts/{filename}/:
    put:
      operationId: upload_artifacts_update
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      consumes: []
      tags:
        - upload
    parameters:
      - name: filename
        in: path
        required: true
        type: string
definitions:
  Cafeteria:
    required:
      - name
      - description
      - sub_description
      - longitude
      - latitude
      - logo_url
      - address
      - opened_from
      - opened_to
      - occupancy
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      name:
        title: Nazwa
        type: string
        maxLength: 128
        minLength: 1
      description:
        title: Opis
        type: string
        maxLength: 256
        minLength: 1
      sub_description:
        title: Dodatkowy opis
        type: string
        maxLength: 512
        minLength: 1
      longitude:
        title: "D\u0142ugo\u015B\u0107 geograficzna"
        type: number
        maximum: 180.0
        minimum: -180.0
      latitude:
        title: "Szeroko\u015B\u0107 geograficzna"
        type: number
        maximum: 90.0
        minimum: -90.0
      logo_url:
        title: URL loga
        type: string
        maxLength: 2048
        minLength: 1
      address:
        title: Adres
        type: string
        maxLength: 256
        minLength: 1
      opened_from:
        title: Otwarta od
        type: string
      opened_to:
        title: Otwarta do
        type: string
      occupancy:
        title: "Liczba os\xF3b w sto\u0142\xF3wce"
        type: integer
        maximum: 2147483647
        minimum: 0
      occupancy_relative:
        title: Occupancy relative
        type: string
        readOnly: true
  FixedMenuOption:
    required:
      - name
      - price
      - photo_url
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      name:
        title: Nazwa
        type: string
        maxLength: 128
        minLength: 1
      price:
        title: Cena
        type: number
        minimum: 0.0
      photo_url:
        title: "URL zdj\u0119cia"
        type: string
        maxLength: 2048
        minLength: 1
      avg_review_stars:
        title: "\u015Arednia ocena"
        type: number
        readOnly: true
  FixedMenuOptionReview:
    required:
      - stars
      - author_nick
      - review_time
      - option
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      stars:
        title: Ocena
        type: integer
        maximum: 5
        minimum: 0
      review_text:
        title: Review text
        type: string
        maxLength: 255
        minLength: 1
      author_nick:
        title: Autor
        type: string
        maxLength: 64
        minLength: 1
      review_time:
        title: Czas
        type: string
        format: date-time
      option:
        title: Option
        type: integer
  AverageDishReviewStats:
    type: object
    properties:
      id:
        title: Id
        type: integer
        readOnly: true
      timestamp:
        title: Timestamp
        type: string
        format: date-time
        readOnly: true
      value:
        title: Value
        type: number
        readOnly: true
  OccupancyStats:
    type: object
    properties:
      id:
        title: Id
        type: integer
        readOnly: true
      timestamp:
        title: Timestamp
        type: string
        format: date-time
        readOnly: true
      occupancy:
        title: Occupancy
        type: integer
        readOnly: true
      occupancy_relative:
        title: Occupancy relative
        type: number
        readOnly: true
  CameraEvent:
    required:
      - event_type
      - timestamp
    type: object
    properties:
      event_type:
        title: Typ zdarzenia
        type: integer
        enum:
          - 0
          - 1
          - 2
          - 3
          - 4
      timestamp:
        title: Czas
        type: string
        format: date-time
      event_value:
        title: "Warto\u015B\u0107 zdarzenia"
        type: integer
        maximum: 2147483647
        minimum: 0
        x-nullable: true
