name: API checks

on:
  pull_request:
    paths:
    - '.github/workflows/api_checks.yaml'
    - 'specs/api.yaml'
  push:
    branches:
    - master

jobs:
  validate-openapi-schema:
    runs-on: ubuntu-latest
    steps:
    - name: Spectral Linting
      uses: stoplightio/spectral-action@v0.5.5
      with:
        file_glob: specs/api.yaml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
