name: Camera CQ

on:
  pull_request:
    paths:
    - '.github/workflows/camera_cq.yaml'
    - 'camera/**.py'
  push:
    branches:
    - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        cd "camera/rpi-files/" &&
        ./setup-environment.sh &&
        cd -
    - name: Lint with flake8/wemake
      run: |
        cd "camera/rpi-files/" &&
        pipenv run flake8 --config=setup.cfg &&
        cd -
    - name: Test with pytest
      run: |
        cd "camera/rpi-files/" &&
        pipenv run pytest &&
        cd -
