name: Camera CQ

on:
  pull_request:
    paths:
    - '.github/workflows/camera_cq.yaml'
    - 'camera/**.py'
  push:
    branches:
    - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        cd "camera/rpi-files/" &&
        ./setup-environment.sh &&
        cd -
    - name: Lint with wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.13.4
      with:
        path: 'camera/rpi-files/'
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
    - name: Test with pytest
      run: |
        cd "camera/rpi-files/" &&
        pipenv run pytest &&
        cd -
