name: Camera CQ

on:
  pull_request:
    paths: ['camera/**.py']

jobs:
  enforce_style_guide:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@master
      with:
        path: 'camera/'
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}

