name: Camera CQ

on:
  pull_request:
    paths:
    - '.github/workflows/camera_cq.yaml'
    - 'camera/**.py'
  push:
    branches:
    - master

jobs:
  enforce_style_guide:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.13.4
      with:
        path: 'camera/rpi-files/'
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install pipenv &&
        cd "camera/rpi-files/" &&
        pipenv install &&
        cd -
    - name: Test with pytest
      run: |
        cd "camera/rpi-files/" &&
        pipenv shell &&
        pytest "."
