name: Webserver deploy for production

on:
  push:
    branches:
    - 'master'
    paths:
    - 'django-server/**'
    - '.github/workflows/server_deploy.yaml'

jobs:
  build:
    name: Checkout and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}                                                              # checkout to branch which was pushed
      - name: Deploy to Heroku
        if: job.status == 'success'
        run: |
          rm -rf .git
          git clone https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/eaterslab.git # clone repo from heroku server
          cd eaterslab                                                                        # folder on deploy server
          find . -maxdepth 1 ! -path './.git' ! -path '.' -exec rm -rf {} +                   # remove all files excluding git repo info and current path
          git config --global user.email "${{ secrets.HEROKU_DEPLOY_EMAIL }}"                 # deploy as specified user
          git config --global user.name "${{ secrets.HEROKU_DEPLOY_NAME }}"
          git commit . -m "cleaned local repo"                                                # commit and push all files
          cp -r ../django-server/server/* ./                                                  # copy new version of server
          git add .
          git commit . -m "deploy full refresh from ${{ github.ref }}"                        # commit and push all files
          git push
          curl -X POST https://api.github.com/repos/pooh-labs/eaterslab/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.DISPATCH_KEY }} --data '{"event_type": "ping"}' # run the android build with upload to server after server update
