name: Webserver deploy

on: push

jobs:
  build:
    name: Checkout and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Deploy to Heroku
        if: job.status == 'success'
        run: |
          ls -la
          rm -rf .git
          git clone https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/eaterslab.git
          cd eaterslab
          shopt -s extglob
          rm -- !(.git|..|.)
          cp ../django-server/* ./
          ls -la
