name: Webserver deploy

on:
  push:
    paths:
    - 'django-server/**'
    - '.github/workflows/server_deploy.yaml'

jobs:
  build:
    name: Checkout and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}                                                              # checkout to branch which was pushed
      - name: Deploy to Heroku
        if: job.status == 'success'
        run: |
          ls -la
          rm -rf .git                                                                         # mark current folder not as a git repo
          ls -la
          git clone https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/eaterslab.git # clone repo from heroku server
          ls -la
          cd eaterslab                                                                        # folder on deploy server
          ls -la
          find . -maxdepth 1 ! -path './.git' ! -path '.' -exec rm -rf {} +                   # remove all files excluding git repo info and current path
          ls -la
          git commit . -m "cleaned local repo"                                                # commit and push all files
          cp -r ../django-server/server/* ./                                                  # copy new version of server
          ls -la
          git config --global user.email "${{ secrets.HEROKU_DEPLOY_EMAIL }}"                 # deploy as specified user
          git config --global user.name "${{ secrets.HEROKU_DEPLOY_NAME }}"
          git add .
          git commit . -m "deploy full refresh from ${{ github.ref }}"                        # commit and push all files
          git push heroku
