name: Webserver deploy

on: push

jobs:
  build:
    name: Checkout and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Deploy to Heroku
        if: job.status == 'success'
        run: |
          rm -rf .git
          git clone https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/eaterslab.git
          cd eaterslab
          find . -maxdepth 1 ! -path './.git' ! -path '.' -exec rm -rf {} +
          cp -r ../django-server/* ./
          git config --global user.email "${{ secrets.HEROKU_DEPLOY_EMAIL }}"
          git config --global user.name "${{ secrets.HEROKU_DEPLOY_NAME }}"
          git add .
          git commit . -m "deploy full refresh from ${{ github.ref }}"
          git push
