name: Webserver deploy

on: push

jobs:
  build:
    name: Checkout and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
	  ref: ${{ github.ref }}
      - name: Deploy to Heroku
        if: job.status == 'success'
        run: |
	  ls -la
	  rm -rf .git
	  cd django-server
	  git init
	  git add .
	  git commit . -m "deploy commit"
	  ls -la
