name: Webserver deploy

on:
  push:
    branches:
      - server

jobs:
  build:
    name: Build server and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: server
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/server' && job.status == 'success'
        run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/mycanteenapp.git server:master
